---
- name: Import install package tasks
  include_tasks: install-package.yml
  when: not rpi_imager_compile | bool
- name: Import compile tasks
  include_tasks: compile.yml
  when: rpi_imager_compile | bool
